package com.fitness.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember

// CompositionLocal that carries the app-level language code ("en" or "zh").
// Set by MainViewController (iOS) or MainActivity (Android) before the content tree.
val LocalAppLanguage = compositionLocalOf { "en" }

// English string table — mirrors values/strings.xml
private val stringsEn: Map<String, String> = mapOf(
    "analytics_title" to "Data Analytics",
    "analytics_radar_title" to "Muscle Balance",
    "analytics_anatomy_title" to "Physique Focus",
    "analytics_volume_title" to "Total Volume",
    "tab_overview" to "Overview",
    "tab_analytics" to "Analytics",
    "view_front" to "Front",
    "view_back" to "Back",
    "range_week" to "Week",
    "range_month" to "Month",
    "range_year" to "Year",
    "clear_filter" to "Clear Filter",
    "settings_ai_config" to "AI Configuration",
    "settings_ai_api_key" to "API Key",
    "settings_ai_base_url" to "Base URL",
    "settings_ai_model" to "Model Name",
    "ai_config_hint" to "Enter your API key and endpoint to enable AI coaching.",
    "ai_generate_insight" to "Generate AI Insight",
    "ai_insight_loading" to "Analyzing your progress...",
    "ai_insight_title" to "AI Coaching Insight",
    "ai_coach_title" to "AI Fitness Coach",
    "ai_coach_hint" to "Ask me about your workout data...",
    "default_username" to "Fitness Enthusiast",
    "app_name" to "FitBot",
    "nav_library" to "Library",
    "nav_plans" to "Plans",
    "nav_profile" to "Profile",
    "cloud_connect" to "Connect Cloud",
    "cloud_connected" to "Cloud Connected",
    "category_all" to "All",
    "current_plan" to "Current Training Plan",
    "no_plan" to "No plan yet, click below to create",
    "update_plan" to "Update Plan",
    "current_tag" to "Current",
    "profile_title" to "Profile",
    "heatmap_title" to "Workout Heatmap",
    "settings_general" to "General Settings",
    "settings_title" to "Settings",
    "settings_theme" to "Theme Mode",
    "settings_language" to "Language",
    "logout" to "Logout",
    "cloud_sync_title" to "Cloud Sync",
    "cloud_disconnected" to "Not Connected",
    "sync_now" to "Sync Now",
    "syncing" to "Syncing...",
    "weight_kg" to "Weight (kg)",
    "reps" to "Reps",
    "session_history" to "Current Session History:",
    "finish_workout" to "Finish workout and sync",
    "session_progress" to "Training Progress:",
    "finish_session" to "Finish Session",
    "training_session" to "Training Session",
    "dialog_cancel" to "Cancel",
    "lang_zh" to "简体中文",
    "lang_en" to "English",
    "week_overview" to "This Week's Overview",
    "today_task" to "Today's Task",
    "rest_message" to "Rest day today! Enjoy your recovery.",
    "training_completed" to "Today's training is completed! Well done!",
    "start_training" to "Start Training",
    "today_badge" to "Today",
    "rest_badge" to "Rest",
    "day_mon" to "Monday",
    "day_tue" to "Tuesday",
    "day_wed" to "Wednesday",
    "day_thu" to "Thursday",
    "day_fri" to "Friday",
    "day_sat" to "Saturday",
    "day_sun" to "Sunday",
    "weekly_routine_name" to "Daily Routine",
    "create_routine" to "Create Weekly Routine",
    "edit_day" to "Edit Day",
    "save" to "Save",
    "add_exercise" to "Add Exercise",
    "set_rest_day" to "Set as Rest Day",
    "set_training_day" to "Set as Training Day",
    "target_sets" to "Sets",
    "remove_exercise" to "Remove exercise?",
    "confirm_remove" to "Remove",
    "login_drive" to "Login to Google Drive",
    "theme_system" to "System Default",
    "theme_light" to "Light",
    "theme_dark" to "Dark",
    "edit_quote" to "Edit Quote",
    "add_record" to "Add Record",
    "edit_record" to "Edit Record",
    "delete" to "Delete",
    "history_title" to "Training History",
    "history_empty" to "No records yet. Start training!",
    "detail_target_muscle" to "Target Muscle",
    "detail_instructions" to "Instructions",
    "kg" to "kg",
    "back" to "Back",
    "cat_chest" to "Chest",
    "cat_back" to "Back",
    "cat_legs" to "Legs",
    "cat_shoulders" to "Shoulders",
    "cat_arms" to "Arms",
    "cat_core" to "Core",
    "cat_full_body" to "Full Body",
    "cat_cardio" to "Cardio",
    "muscle_chest" to "Pectorals",
    "muscle_upper_chest" to "Upper Pectorals",
    "muscle_lats" to "Latissimus Dorsi",
    "muscle_mid_back" to "Middle Back",
    "muscle_lower_back" to "Lower Back",
    "muscle_quads" to "Quadriceps",
    "muscle_glutes_legs" to "Glutes & Legs",
    "muscle_calves" to "Calves",
    "muscle_shoulders" to "Deltoids",
    "muscle_biceps" to "Biceps",
    "muscle_triceps" to "Triceps",
    "muscle_abs" to "Abdominals",
    "muscle_full_body" to "Full Body",
    "muscle_cardio" to "Cardiovascular",
    "ex_running_name" to "Running",
    "ex_brisk_walking_name" to "Brisk Walking",
    "ex_cycling_name" to "Cycling",
    "ex_running_desc" to "A continuous, rhythmic activity that uses large muscle groups and gets the heart pumping.",
    "ex_brisk_walking_desc" to "Walking at a faster-than-average pace, great for cardiovascular health.",
    "ex_cycling_desc" to "Riding a bicycle for cardiovascular fitness and lower body endurance.",
    "ex_benchpress_name" to "Bench Press",
    "ex_pushup_name" to "Push-up",
    "ex_incline_press_name" to "Incline Bench Press",
    "ex_pullup_name" to "Pull-up",
    "ex_row_name" to "Barbell Row",
    "ex_deadlift_name" to "Deadlift",
    "ex_squat_name" to "Squat",
    "ex_lunge_name" to "Lunge",
    "ex_calf_raise_name" to "Calf Raise",
    "ex_overhead_press_name" to "Overhead Press",
    "ex_lateral_raise_name" to "Lateral Raise",
    "ex_bicep_curl_name" to "Bicep Curl",
    "ex_tricep_dips_name" to "Tricep Dips",
    "ex_situp_name" to "Sit-up",
    "ex_crunches_name" to "Crunches",
    "ex_russian_twist_name" to "Russian Twist",
    "ex_plank_name" to "Plank",
    "ex_burpee_name" to "Burpee",
    "ex_benchpress_desc" to "Lie on a bench and press the barbell vertically.",
    "ex_pushup_desc" to "Standard bodyweight chest exercise.",
    "ex_incline_press_desc" to "Focuses on the upper chest.",
    "ex_pullup_desc" to "The king of back exercises.",
    "ex_row_desc" to "Increases back thickness.",
    "ex_deadlift_desc" to "Fundamental powerlifting movement for the whole posterior chain.",
    "ex_squat_desc" to "An all-around leg exercise.",
    "ex_lunge_desc" to "Unilateral leg strength training.",
    "ex_calf_raise_desc" to "Isolates and strengthens the calf muscles.",
    "ex_overhead_press_desc" to "Primary movement for building strong shoulders.",
    "ex_lateral_raise_desc" to "Isolates the side deltoids for shoulder width.",
    "ex_bicep_curl_desc" to "Classic arm isolation for the biceps.",
    "ex_tricep_dips_desc" to "Bodyweight or weighted exercise for triceps and chest.",
    "ex_situp_desc" to "Classic core exercise for abdominal strength.",
    "ex_crunches_desc" to "Targeted upper abdominal isolation.",
    "ex_russian_twist_desc" to "Rotational core exercise for the obliques.",
    "ex_plank_desc" to "Core stability training.",
    "ex_burpee_desc" to "High-intensity full-body exercise."
)

// Chinese string table — mirrors values-zh/strings.xml
private val stringsZh: Map<String, String> = mapOf(
    "analytics_title" to "数据分析",
    "analytics_radar_title" to "肌肉均衡度",
    "analytics_anatomy_title" to "体型热力图",
    "analytics_volume_title" to "总训练容量",
    "tab_overview" to "概览",
    "tab_analytics" to "分析",
    "view_front" to "正面",
    "view_back" to "背面",
    "range_week" to "周",
    "range_month" to "月",
    "range_year" to "年",
    "clear_filter" to "清除过滤",
    "settings_ai_config" to "AI 配置",
    "settings_ai_api_key" to "API 密钥 (API Key)",
    "settings_ai_base_url" to "接口地址 (Base URL)",
    "settings_ai_model" to "模型名称 (Model)",
    "ai_config_hint" to "输入您的 API 密钥和接口地址以启用 AI 私教功能。",
    "ai_generate_insight" to "生成 AI 训练建议",
    "ai_insight_loading" to "正在为您深度分析进度...",
    "ai_insight_title" to "AI 私教洞察",
    "ai_coach_title" to "AI 私教",
    "ai_coach_hint" to "问问我关于训练数据的问题...",
    "default_username" to "健身达人",
    "app_name" to "FitBot",
    "nav_library" to "动作库",
    "nav_plans" to "训练计划",
    "nav_profile" to "个人中心",
    "cloud_connect" to "连接云盘",
    "cloud_connected" to "云盘已连接",
    "category_all" to "全部",
    "current_plan" to "当前训练计划",
    "no_plan" to "暂无计划，请点击下方按钮创建",
    "update_plan" to "更新计划",
    "current_tag" to "当前",
    "profile_title" to "个人中心",
    "heatmap_title" to "训练热力图",
    "settings_general" to "通用设置",
    "settings_title" to "设置",
    "settings_theme" to "主题模式",
    "settings_language" to "语言 (Language)",
    "logout" to "退出登录",
    "cloud_sync_title" to "云同步",
    "cloud_disconnected" to "未连接",
    "sync_now" to "立即同步",
    "syncing" to "正在同步...",
    "weight_kg" to "重量 (kg)",
    "reps" to "次数",
    "session_history" to "当前动作组数记录:",
    "finish_workout" to "完成训练并同步",
    "session_progress" to "训练进度:",
    "finish_session" to "结束会话",
    "training_session" to "训练会话",
    "dialog_cancel" to "取消",
    "lang_zh" to "简体中文",
    "lang_en" to "English",
    "week_overview" to "本周安排总览",
    "today_task" to "今日任务",
    "rest_message" to "今天是休息日，好好放松一下吧！",
    "training_completed" to "今天的训练已完成！干得漂亮！",
    "start_training" to "开始训练",
    "today_badge" to "今天",
    "rest_badge" to "休息",
    "day_mon" to "星期一",
    "day_tue" to "星期二",
    "day_wed" to "星期三",
    "day_thu" to "星期四",
    "day_fri" to "星期五",
    "day_sat" to "星期六",
    "day_sun" to "星期日",
    "weekly_routine_name" to "日训练计划",
    "create_routine" to "创建周训练计划",
    "edit_day" to "编辑单日安排",
    "save" to "保存",
    "add_exercise" to "添加动作",
    "set_rest_day" to "设为休息日",
    "set_training_day" to "设为训练日",
    "target_sets" to "目标组数",
    "remove_exercise" to "确认移除该动作？",
    "confirm_remove" to "移除",
    "login_drive" to "登录 Google Drive",
    "theme_system" to "跟随系统",
    "theme_light" to "浅色",
    "theme_dark" to "深色",
    "edit_quote" to "编辑座右铭",
    "add_record" to "添加记录",
    "edit_record" to "编辑记录",
    "delete" to "删除",
    "history_title" to "训练记录",
    "history_empty" to "暂无记录，开始训练吧！",
    "detail_target_muscle" to "目标肌肉",
    "detail_instructions" to "动作要领",
    "kg" to "kg",
    "back" to "返回",
    "cat_chest" to "胸部",
    "cat_back" to "背部",
    "cat_legs" to "腿部",
    "cat_shoulders" to "肩部",
    "cat_arms" to "手臂",
    "cat_core" to "核心",
    "cat_full_body" to "全身",
    "cat_cardio" to "有氧",
    "muscle_chest" to "胸大肌",
    "muscle_upper_chest" to "胸大肌上束",
    "muscle_lats" to "背阔肌",
    "muscle_mid_back" to "中背部",
    "muscle_lower_back" to "下背部",
    "muscle_quads" to "股四头肌",
    "muscle_glutes_legs" to "臀腿部",
    "muscle_calves" to "小腿肌群",
    "muscle_shoulders" to "三角肌",
    "muscle_biceps" to "肱二头肌",
    "muscle_triceps" to "肱三头肌",
    "muscle_abs" to "腹部肌群",
    "muscle_full_body" to "全身",
    "muscle_cardio" to "心肺系统",
    "ex_running_name" to "跑步",
    "ex_brisk_walking_name" to "快走",
    "ex_cycling_name" to "骑行",
    "ex_running_desc" to "一种利用下肢大肌肉群进行的连续、有节奏的心肺训练活动。",
    "ex_brisk_walking_desc" to "以比散步更快的速度行走，极好的有氧健康运动。",
    "ex_cycling_desc" to "使用自行车进行的下肢耐力与心肺训练。",
    "ex_benchpress_name" to "杠铃卧推",
    "ex_pushup_name" to "俯卧撑",
    "ex_incline_press_name" to "上斜卧推",
    "ex_pullup_name" to "引体向上",
    "ex_row_name" to "划船",
    "ex_deadlift_name" to "硬拉",
    "ex_squat_name" to "深蹲",
    "ex_lunge_name" to "箭步蹲",
    "ex_calf_raise_name" to "提踵",
    "ex_overhead_press_name" to "推举",
    "ex_lateral_raise_name" to "侧平举",
    "ex_bicep_curl_name" to "杠铃弯举",
    "ex_tricep_dips_name" to "臂屈伸",
    "ex_situp_name" to "仰卧起坐",
    "ex_crunches_name" to "卷腹",
    "ex_russian_twist_name" to "俄罗斯转体",
    "ex_plank_name" to "平板支撑",
    "ex_burpee_name" to "波比跳",
    "ex_benchpress_desc" to "仰卧在凳子上，垂直推起杠铃。",
    "ex_pushup_desc" to "标准的自重胸部训练。",
    "ex_incline_press_desc" to "侧重胸肌上部。",
    "ex_pullup_desc" to "背部王牌动作。",
    "ex_row_desc" to "增加背部厚度。",
    "ex_deadlift_desc" to "锻炼后侧链（背、臀、腿）的王牌力量动作。",
    "ex_squat_desc" to "全能练腿动作。",
    "ex_lunge_desc" to "单腿力量训练。",
    "ex_calf_raise_desc" to "孤立锻炼小腿肌肉，提升爆发力。",
    "ex_overhead_press_desc" to "构建强壮肩部的核心动作。",
    "ex_lateral_raise_desc" to "孤立锻炼三角肌中束，增加肩部宽度。",
    "ex_bicep_curl_desc" to "锻炼肱二头肌的经典动作。",
    "ex_tricep_dips_desc" to "自重或负重锻炼肱三头肌和胸肌下缘。",
    "ex_situp_desc" to "经典的腹部力量训练动作。",
    "ex_crunches_desc" to "针对上腹部的孤立训练。",
    "ex_russian_twist_desc" to "锻炼腹内外斜肌的旋转动作。",
    "ex_plank_desc" to "核心稳定性训练。",
    "ex_burpee_desc" to "高强度全身训练。"
)

/**
 * Returns the localized string for [key] using the provided [language] code.
 */
fun getLocalizedTypedString(key: String, language: String): String {
    val baseLanguage = language.split("-")[0].lowercase()
    val table = if (baseLanguage == "zh") stringsZh else stringsEn
    return table[key] ?: key
}

/**
 * Returns the localized string for [key] using the language set in [LocalAppLanguage].
 */
@Composable
fun getString(key: String): String {
    val language = LocalAppLanguage.current
    return getLocalizedTypedString(key, language)
}
