name: FitBot
options:
  bundleIdPrefix: com.fitness
targets:
  FitBot:
    type: application
    platform: iOS
    deploymentTarget: "14.1"
    sources:
      - iosApp
    settings:
      base:
        INFOPLIST_FILE: iosApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fitness.FitBot
        MARKETING_VERSION: 0.4.1
        CURRENT_PROJECT_VERSION: 9
        PRODUCT_NAME: FitBot
        DEVELOPMENT_TEAM: ""

schemes:
  FitBot:
    build:
      targets:
        FitBot: [run, test, profile, analyze, archive]
    run:
      config: Debug
    archive:
      config: Release
