package com.fitness.util

import androidx.compose.runtime.Composable

private val stringMap = mapOf(
    "app_name" to "FitBot",
    "nav_library" to "Library",
    "nav_plans" to "Plans",
    "nav_profile" to "Profile",
    "category_all" to "All",
    "cat_chest" to "Chest",
    "cat_back" to "Back",
    "cat_legs" to "Legs",
    "cat_shoulders" to "Shoulders",
    "cat_arms" to "Arms",
    "cat_core" to "Core",
    "cat_full_body" to "Full Body",
    "ex_benchpress_name" to "Bench Press",
    "ex_pushup_name" to "Push-up",
    "ex_incline_press_name" to "Incline Bench Press",
    "ex_pullup_name" to "Pull-up",
    "ex_row_name" to "Barbell Row",
    "ex_deadlift_name" to "Deadlift",
    "ex_squat_name" to "Squat",
    "ex_lunge_name" to "Lunge",
    "ex_calf_raise_name" to "Calf Raise",
    "ex_overhead_press_name" to "Overhead Press",
    "ex_lateral_raise_name" to "Lateral Raise",
    "ex_bicep_curl_name" to "Bicep Curl",
    "ex_tricep_dips_name" to "Tricep Dips",
    "ex_situp_name" to "Sit-up",
    "ex_crunches_name" to "Crunches",
    "ex_russian_twist_name" to "Russian Twist",
    "ex_plank_name" to "Plank",
    "ex_burpee_name" to "Burpee",
    "muscle_chest" to "Pectorals",
    "muscle_upper_chest" to "Upper Chest",
    "muscle_lats" to "Lats",
    "muscle_mid_back" to "Mid Back",
    "muscle_lower_back" to "Lower Back",
    "muscle_quads" to "Quads",
    "muscle_glutes_legs" to "Glutes & Legs",
    "muscle_calves" to "Calves",
    "muscle_shoulders" to "Deltoids",
    "muscle_biceps" to "Biceps",
    "muscle_triceps" to "Triceps",
    "muscle_abs" to "Abs",
    "muscle_full_body" to "Full Body",
    "heatmap_title" to "Workout Heatmap",
    "login_drive" to "Login to Google Drive",
    "logout" to "Logout",
    "settings_title" to "Settings",
    "settings_general" to "General",
    "settings_theme" to "Theme",
    "settings_language" to "Language",
    "theme_system" to "System",
    "theme_light" to "Light",
    "theme_dark" to "Dark",
    "lang_zh" to "Chinese",
    "lang_en" to "English",
    "dialog_cancel" to "Cancel",
    "save" to "Save",
    "edit_quote" to "Edit Quote",
    "cloud_sync_title" to "Cloud Sync",
    "cloud_connected" to "Connected to Google Drive",
    "cloud_disconnected" to "Not Connected",
    "syncing" to "Syncing...",
    "sync_now" to "Sync Now",
    "rest_badge" to "Rest Day",
    "no_plan" to "No Plan Scheduled",
    "create_routine" to "Manage Routine",
    "edit_day" to "Edit Day",
    "current_tag" to "Today",
    "detail_target_muscle" to "Target Muscle",
    "detail_instructions" to "Instructions"
)

@Composable
actual fun getString(key: String): String {
    return stringMap[key] ?: key
}
